"""
api/routes/summaries.py - LLM summary ingest + retrieval
"""
from datetime import datetime, timezone
from typing import Optional
from fastapi import APIRouter
from pydantic import BaseModel, Field
from app.ws.connection_manager import manager as ws_manager

router = APIRouter(prefix="/summaries", tags=["Intelligence (LLM Summaries)"])

_zone_summaries: dict[str, dict] = {}
_shift_report:   Optional[dict]  = None
_explanations:   dict[str, dict] = {}

class ZoneSummaryIngest(BaseModel):
    zone_id: str; zone_name: str; summary: str; risk_level: str = "low"
    key_events: list[str] = Field(default_factory=list)
    person_count: int = 0; alert_count: int = 0; generated_at: str = ""

class ShiftReportIngest(BaseModel):
    report_date: str; shift: str; summary: str
    total_alerts: int = 0; high_severity: int = 0
    recommendations: list[str] = Field(default_factory=list); generated_at: str = ""

class AnomalyExplanationIngest(BaseModel):
    alert_type: str; alert_id: str = ""; person_id: str = ""; camera_id: str = ""
    explanation: str; recommendation: str = ""
    false_positive_probability: str = "medium"; context: str = ""

@router.post("/ingest", status_code=201)
async def ingest_zone_summary(data: ZoneSummaryIngest):
    record = {**data.model_dump(), "generated_at": data.generated_at or datetime.now(timezone.utc).isoformat()}
    _zone_summaries[data.zone_id] = record
    await ws_manager.broadcast({"type": "zone_summary", "payload": record})
    return {"status": "ok", "zone_id": data.zone_id}

@router.post("/shift-report", status_code=201)
async def ingest_shift_report(data: ShiftReportIngest):
    global _shift_report
    _shift_report = {**data.model_dump(), "generated_at": data.generated_at or datetime.now(timezone.utc).isoformat()}
    await ws_manager.broadcast({"type": "shift_report", "payload": _shift_report})
    return {"status": "ok"}

@router.post("/explanation", status_code=201)
async def ingest_explanation(data: AnomalyExplanationIngest):
    _explanations[data.alert_type] = data.model_dump()
    await ws_manager.broadcast({"type": "anomaly_explanation", "payload": data.model_dump()})
    return {"status": "ok"}

@router.get("/zones")
async def get_zone_summaries():
    return {"summaries": list(_zone_summaries.values()), "zone_count": len(_zone_summaries)}

@router.get("/zones/{zone_id}")
async def get_zone_summary(zone_id: str):
    return _zone_summaries.get(zone_id, {
        "zone_id": zone_id, "summary": "No summary yet. AI service generates these every 30 seconds.",
        "risk_level": "unknown", "key_events": [], "person_count": 0, "alert_count": 0
    })

@router.get("/shift-report")
async def get_shift_report():
    return _shift_report or {
        "summary": "No shift report yet. Reports generate every 30 seconds when AI service is running.",
        "total_alerts": 0, "high_severity": 0,
        "recommendations": ["Start AI service with USE_LLM=true to enable reports."], "shift": "unknown"
    }

@router.get("/explanation/{alert_type}")
async def get_explanation(alert_type: str):
    defaults = {
        "unauthorized_access": ("Person detected in a restricted zone without authorization. Security response required.", "Escort individual out and review access logs."),
        "loitering": ("Person stationary in an area beyond expected dwell time.", "Security patrol should verify the individual."),
        "worker_fall": ("Worker posture indicates possible fall event.", "Dispatch first aid immediately."),
        "ppe_violation": ("Missing PPE in mandatory compliance zone.", "Remind worker and log the violation."),
        "suspicious_activity": ("Movement inconsistent with normal operations.", "Security patrol to verify situation."),
    }
    if alert_type in _explanations:
        return _explanations[alert_type]
    d = defaults.get(alert_type, ("Alert generated by CV rules engine.", "Verify situation manually."))
    return {"alert_type": alert_type, "explanation": d[0], "recommendation": d[1], "false_positive_probability": "medium"}
