"""
services/alert_service.py
─────────────────────────
Business logic for the Alert resource.

Alerts are generated by the AI anomaly classifier pipeline and
consumed by the dashboard Alert Panel.
"""

from typing import Optional
from app.core.config import settings
from app.services.mock_data import MOCK_ALERTS
from app.schemas.alert import AlertOut, AlertStatus


async def get_all_alerts(
    status:   Optional[str] = None,
    severity: Optional[str] = None,
    zone:     Optional[str] = None,
    camera_id: Optional[str] = None,
    limit:    int = 50,
) -> list[AlertOut]:
    """
    Return alerts with optional filters.

    Args:
        status:    "active" | "resolved"
        severity:  "low" | "medium" | "high"
        zone:      zone name
        camera_id: filter by specific camera
        limit:     max number of results (default 50)

    Returns:
        List of AlertOut, newest first.
    """
    if settings.USE_MOCK_DATA:
        alerts = MOCK_ALERTS.copy()

        if status:    alerts = [a for a in alerts if a["status"]    == status]
        if severity:  alerts = [a for a in alerts if a["severity"]  == severity]
        if zone:      alerts = [a for a in alerts if a["zone"]      == zone]
        if camera_id: alerts = [a for a in alerts if a["camera_id"] == camera_id]

        # Sort newest first
        alerts.sort(key=lambda a: a["triggered_at"], reverse=True)

        return [AlertOut(**a) for a in alerts[:limit]]

    raise NotImplementedError("Database not yet connected.")


async def get_alert_by_id(alert_id: str) -> Optional[AlertOut]:
    """Return a single alert by ID, or None if not found."""
    if settings.USE_MOCK_DATA:
        for a in MOCK_ALERTS:
            if a["id"] == alert_id:
                return AlertOut(**a)
        return None

    raise NotImplementedError("Database not yet connected.")


async def resolve_alert(alert_id: str, resolved_by: str) -> Optional[AlertOut]:
    """
    Mark an alert as resolved.

    Args:
        alert_id:    ID of the alert to resolve
        resolved_by: email/username of the operator

    Returns:
        Updated AlertOut, or None if not found.
    """
    if settings.USE_MOCK_DATA:
        from datetime import datetime
        from zoneinfo import ZoneInfo
        for alert in MOCK_ALERTS:
            if alert["id"] == alert_id:
                alert["status"]      = AlertStatus.RESOLVED
                alert["resolved_by"] = resolved_by
                alert["resolved_at"] = datetime.now(ZoneInfo("UTC"))
                return AlertOut(**alert)
        return None

    raise NotImplementedError("Database not yet connected.")


async def get_active_alert_count() -> int:
    """Quick count of unresolved alerts — used by the analytics summary."""
    if settings.USE_MOCK_DATA:
        return sum(1 for a in MOCK_ALERTS if a["status"] == "active")
    raise NotImplementedError("Database not yet connected.")
