// components/intelligence/IntelligencePanel.tsx
//
// The Intelligence Panel shows AI-generated understanding of warehouse activity:
//
//   Zone Intelligence Tab:
//     LLM-generated summaries for each zone, updated every few minutes.
//     Risk badges, person counts, key events, and natural-language paragraphs.
//
//   Shift Report Tab:
//     Consolidated shift summary with recommendations.
//     Generated by an LLM from all zone summaries.
//
//   AI Explanations Tab:
//     When a HIGH-severity alert fires, the LLM explains why it's suspicious
//     and what security should do. Live-streamed via WebSocket.
//
// Data flow:
//   AI service → ZoneSummarizer → POST /api/v1/summaries/ingest
//                               → WS broadcast { type: "zone_summary" }
//                               → useIntelligenceStore.setZoneSummary()
//                               → this component re-renders

import { useState } from 'react'
import { useQuery } from '@tanstack/react-query'
import { formatDistanceToNow } from 'date-fns'
import {
  Brain, AlertTriangle, RefreshCw,
  Users, Clock, ChevronRight,
  Sparkles, ShieldAlert
} from 'lucide-react'
import { useIntelligenceStore } from '../../store/intelligenceStore'

// ── Risk badge ────────────────────────────────────────────────────────────────
function RiskBadge({ level }: { level: string }) {
  const map: Record<string, string> = {
    high:    'badge-high',
    medium:  'badge-medium',
    low:     'badge-ok',
    unknown: 'text-[10px] font-mono px-2 py-0.5 rounded-sm border border-surface-600 text-text-muted',
  }
  return <span className={map[level] ?? map.unknown}>{level.toUpperCase()}</span>
}

// ── Zone summary card ─────────────────────────────────────────────────────────
function ZoneSummaryCard({ summary }: { summary: any }) {
  const [expanded, setExpanded] = useState(false)

  return (
    <div
      className="card-sm cursor-pointer hover:border-surface-500 transition-colors"
      onClick={() => setExpanded(!expanded)}
    >
      <div className="flex items-start justify-between gap-3">
        <div className="flex-1 min-w-0">
          <div className="flex items-center gap-2 mb-1.5 flex-wrap">
            <span className="text-sm font-semibold text-text-primary">{summary.zone_name}</span>
            <RiskBadge level={summary.risk_level} />
          </div>
          <p className={`text-xs text-text-secondary leading-relaxed ${expanded ? '' : 'line-clamp-2'}`}>
            {summary.summary}
          </p>
        </div>
        <ChevronRight
          size={14}
          className={`text-text-muted flex-shrink-0 transition-transform mt-0.5 ${expanded ? 'rotate-90' : ''}`}
        />
      </div>

      {expanded && (
        <div className="mt-3 pt-3 border-t border-surface-700 space-y-2 animate-fade-in">
          {/* Stats row */}
          <div className="grid grid-cols-3 gap-2">
            {[
              { icon: <Users size={11} />,   label: 'Persons',  val: summary.person_count },
              { icon: <AlertTriangle size={11} />, label: 'Alerts', val: summary.alert_count },
              { icon: <Clock size={11} />,   label: 'Updated',  val: formatDistanceToNow(new Date(summary.generated_at), { addSuffix: true }) },
            ].map(({ icon, label, val }) => (
              <div key={label} className="bg-surface-700/50 rounded-lg px-2 py-1.5 text-center">
                <div className="flex items-center justify-center gap-1 text-text-muted mb-0.5">{icon}</div>
                <div className="text-xs font-mono font-medium text-text-primary">{val}</div>
                <div className="text-[10px] text-text-muted uppercase tracking-wider">{label}</div>
              </div>
            ))}
          </div>

          {/* Key events */}
          {summary.key_events?.length > 0 && (
            <div>
              <p className="text-[10px] text-text-muted uppercase tracking-widest mb-1.5">Key Events</p>
              <ul className="space-y-1">
                {summary.key_events.map((evt: string, i: number) => (
                  <li key={i} className="flex items-start gap-2 text-xs text-text-secondary">
                    <span className="text-accent-cyan mt-0.5 flex-shrink-0">›</span>
                    <span>{evt}</span>
                  </li>
                ))}
              </ul>
            </div>
          )}
        </div>
      )}
    </div>
  )
}

// ── Shift report tab ──────────────────────────────────────────────────────────
function ShiftReportTab() {
  const storeReport = useIntelligenceStore(s => s.shiftReport)

  const { data: fetchedReport, isLoading } = useQuery({
    queryKey: ['shift-report'],
    queryFn:  () => fetch('/api/v1/summaries/shift-report').then(r => r.json()),
    refetchInterval: 120_000,
    enabled:  !storeReport,
  })

  const report = storeReport ?? fetchedReport

  if (isLoading) return (
    <div className="p-6 text-center text-text-muted text-sm animate-pulse">
      Loading shift report…
    </div>
  )

  if (!report) return (
    <div className="p-6 text-center text-text-muted text-sm">
      No shift report yet — will generate after a few minutes of monitoring.
    </div>
  )

  return (
    <div className="space-y-4">
      {/* Header */}
      <div className="flex items-center justify-between">
        <div>
          <h3 className="text-sm font-semibold text-text-primary">
            {report.shift?.charAt(0).toUpperCase() + report.shift?.slice(1)} Shift Report
          </h3>
          {report.report_date && (
            <p className="text-[11px] text-text-muted">{report.report_date}</p>
          )}
        </div>
        <div className="text-right">
          <div className="text-lg font-bold font-mono text-accent-red">{report.total_alerts ?? 0}</div>
          <div className="text-[10px] text-text-muted">Total alerts</div>
        </div>
      </div>

      {/* Summary */}
      <div className="card-sm">
        <div className="flex items-center gap-2 mb-2">
          <Sparkles size={13} className="text-accent-cyan" />
          <span className="text-xs font-semibold text-text-secondary uppercase tracking-wider">
            AI Summary
          </span>
        </div>
        <p className="text-sm text-text-primary leading-relaxed">{report.summary}</p>
      </div>

      {/* Stats */}
      <div className="grid grid-cols-2 gap-3">
        <div className="card-sm">
          <div className="text-xl font-bold font-mono text-accent-amber">{report.high_severity ?? 0}</div>
          <div className="text-xs text-text-muted uppercase tracking-wider">High Severity</div>
        </div>
        <div className="card-sm">
          <div className="text-xl font-bold font-mono text-accent-cyan">
            {report.generated_at ? formatDistanceToNow(new Date(report.generated_at), { addSuffix: true }) : '—'}
          </div>
          <div className="text-xs text-text-muted uppercase tracking-wider">Generated</div>
        </div>
      </div>

      {/* Recommendations */}
      {report.recommendations?.length > 0 && (
        <div className="card-sm">
          <p className="text-[10px] text-text-muted uppercase tracking-widest mb-2">
            AI Recommendations
          </p>
          <ul className="space-y-2">
            {report.recommendations.map((rec: string, i: number) => (
              <li key={i} className="flex items-start gap-2 text-xs text-text-secondary">
                <span className="text-accent-green font-mono mt-0.5 flex-shrink-0">{i + 1}.</span>
                <span>{rec}</span>
              </li>
            ))}
          </ul>
        </div>
      )}
    </div>
  )
}

// ── AI Explanations tab ───────────────────────────────────────────────────────
function ExplanationsTab() {
  const explanations = useIntelligenceStore(s => s.explanations)

  if (explanations.length === 0) return (
    <div className="flex flex-col items-center justify-center py-12 text-text-muted">
      <ShieldAlert size={28} className="mb-3 opacity-30" />
      <p className="text-sm">No AI explanations yet</p>
      <p className="text-xs mt-1">High-severity alerts trigger automatic LLM analysis</p>
    </div>
  )

  return (
    <div className="space-y-3">
      {explanations.map((exp, i) => (
        <div key={i} className="card-sm border-red-900/30 animate-slide-in">
          <div className="flex items-center gap-2 mb-2">
            <ShieldAlert size={13} className="text-accent-red flex-shrink-0" />
            <span className="text-xs font-semibold text-accent-red">
              {exp.alert_type.replace(/_/g, ' ').toUpperCase()}
            </span>
            <span className="text-[10px] font-mono text-text-muted ml-auto">
              {exp.person_id} · {exp.camera_id}
            </span>
          </div>

          <div className="space-y-2">
            <div>
              <p className="text-[10px] text-text-muted uppercase tracking-widest mb-1">Why flagged</p>
              <p className="text-xs text-text-secondary leading-relaxed">{exp.explanation}</p>
            </div>

            {exp.recommendation && (
              <div>
                <p className="text-[10px] text-text-muted uppercase tracking-widest mb-1">Action</p>
                <p className="text-xs text-accent-green">{exp.recommendation}</p>
              </div>
            )}

            <div className="flex items-center gap-3 text-[10px] font-mono text-text-muted">
              <span>False positive: <span className={
                exp.false_positive === 'low' ? 'text-accent-green' :
                exp.false_positive === 'high' ? 'text-accent-amber' : 'text-text-secondary'
              }>{exp.false_positive}</span></span>
              <span>·</span>
              <span>{formatDistanceToNow(new Date(exp.timestamp), { addSuffix: true })}</span>
            </div>
          </div>
        </div>
      ))}
    </div>
  )
}

// ── Main component ────────────────────────────────────────────────────────────

type Tab = 'zones' | 'report' | 'explanations'

export function IntelligencePanel() {
  const [tab, setTab] = useState<Tab>('zones')
  const storeZones    = useIntelligenceStore(s => s.zoneSummaries)
  const explanations  = useIntelligenceStore(s => s.explanations)

  // Fetch initial zone summaries from backend
  const { data: fetchedZones, isLoading, refetch } = useQuery({
    queryKey: ['zone-summaries'],
    queryFn:  () => fetch('/api/v1/summaries/zones').then(r => r.json()).then(d => d.summaries ?? []),
    refetchInterval: 120_000,
  })

  // Merge store (live WS) + fetched (initial load)
  const zoneSummaries = Object.keys(storeZones).length > 0
    ? Object.values(storeZones)
    : (fetchedZones ?? [])

  const tabs: { key: Tab; label: string; count?: number }[] = [
    { key: 'zones',        label: 'Zone Intelligence', count: zoneSummaries.length },
    { key: 'report',       label: 'Shift Report' },
    { key: 'explanations', label: 'AI Explanations', count: explanations.length },
  ]

  return (
    <div className="card flex flex-col h-full overflow-hidden">
      {/* Header */}
      <div className="flex items-center justify-between pb-3 border-b border-surface-600 flex-shrink-0">
        <div className="flex items-center gap-2">
          <Brain size={15} className="text-accent-cyan" />
          <span className="text-sm font-semibold text-text-primary">AI Intelligence</span>
          <span className="text-[10px] font-mono px-1.5 py-0.5 rounded bg-cyan-950/60 text-accent-cyan border border-cyan-900">
            VLM+LLM
          </span>
        </div>
        <button
          onClick={() => refetch()}
          className="text-text-muted hover:text-text-secondary transition-colors p-1"
          title="Refresh"
        >
          <RefreshCw size={12} />
        </button>
      </div>

      {/* Tabs */}
      <div className="flex gap-1 py-2 flex-shrink-0">
        {tabs.map(t => (
          <button
            key={t.key}
            onClick={() => setTab(t.key)}
            className={`flex items-center gap-1.5 px-2.5 py-1 rounded-md text-xs font-medium transition-colors ${
              tab === t.key
                ? 'bg-surface-600 text-text-primary'
                : 'text-text-muted hover:text-text-secondary'
            }`}
          >
            {t.label}
            {t.count !== undefined && t.count > 0 && (
              <span className="text-[9px] bg-surface-600 px-1 rounded font-mono">{t.count}</span>
            )}
          </button>
        ))}
      </div>

      {/* Content */}
      <div className="flex-1 overflow-y-auto space-y-2">
        {tab === 'zones' && (
          isLoading ? (
            <div className="p-4 text-center text-text-muted text-sm animate-pulse">
              Loading zone summaries…
            </div>
          ) : zoneSummaries.length === 0 ? (
            <div className="flex flex-col items-center justify-center py-10 text-text-muted">
              <Brain size={28} className="mb-3 opacity-30" />
              <p className="text-sm">Summaries generating…</p>
              <p className="text-xs mt-1 text-center max-w-xs">
                The AI service generates zone summaries every few minutes.
                Make sure the AI service is running.
              </p>
            </div>
          ) : (
            zoneSummaries.map((s: any) => (
              <ZoneSummaryCard key={s.zone_id} summary={s} />
            ))
          )
        )}
        {tab === 'report'       && <ShiftReportTab />}
        {tab === 'explanations' && <ExplanationsTab />}
      </div>
    </div>
  )
}
